    name: Hello World Workflow

    on:
      workflow_dispatch:
        inputs:
            record_id:
                type: string

    jobs:
      call-api:
        runs-on: ubuntu-latest
        steps:
          - name: Make an API call with curl
            run: | 
                curl --location --request PUT 'https://helixdemoash2739-demo-restapi.onbmc.com/api/arsys/v1/entry/CHG:Infrastructure%20Change/${{github.event.inputs.record_id}}' \
                --header 'Authorization: AR-JWT eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIhPSF7ZW5jfSE9IUFBQUFETEVpaWU3NGRTcldJQ2xLWkp5QWVIdUhzS3hBNVRESWZJZlVxb1ZYYS8ycyIsIl9sb2NhbGVMYW5ndWFnZSI6ImVuIiwibmJmIjoxNzU4MTkzODE5LCJpc3MiOiJwbGF0Zm9ybS1mdHMtMC5wbGF0Zm9ybS1mdHMiLCJfbG9jYWxlQ291bnRyeSI6IlVTIiwiX2F1dGhTdHJpbmciOiIhPSF7ZW5jfSE9IUFBQUFETEVpaWU3NGRTcldJQ2xLWlBzb013eTZyN3JYNnBxbVN3Nm9hR0U9IiwiZXhwIjoxNzU4MjIyNzM5LCJfY2FjaGVJZCI6NzEzMTY0NiwiaWF0IjoxNzU4MTkzOTM5LCJqdGkiOiJJREdBS0ZIVkpHMDYxQVRDU0hFOVRDU0hFOTMzUVoiLCJfYWJzb2x1dGVFeHBpcmF0aW9uVGltZSI6MTc1ODI4MDMzOX0.N6GnptDRPry8drpUxnhX3eZPk2uVuT8yh-iQBpgowyk' \
                --header 'Content-Type: application/json' \
                --data '{ "values": { "Description": "Github Action Run Status : Success;"} }'
