    name: Hello World Workflow

    on:
      workflow_dispatch:
        inputs:
            record_id:
                type: string

    jobs:
      call-api:
        runs-on: ubuntu-latest
        steps:
          - name: Make an API call with curl
            run: | 
                curl --location --request PUT 'https://helixdemoash2739-demo-restapi.onbmc.com/api/arsys/v1/entry/CHG:Infrastructure%20Change/${{github.event.inputs.record_id}}' \
                --header 'Authorization: AR-JWT eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIhPSF7ZW5jfSE9IUFBQUFETEVpaWU3NGRTcldJQ2xLWkp5QWVIdUhzS3hBNVRESWZJZlVxb1ZYYS8ycyIsIl9sb2NhbGVMYW5ndWFnZSI6ImVuIiwibmJmIjoxNzU4MjY3MTg1LCJpc3MiOiJwbGF0Zm9ybS1mdHMtMC5wbGF0Zm9ybS1mdHMiLCJfbG9jYWxlQ291bnRyeSI6IlVTIiwiX2F1dGhTdHJpbmciOiIhPSF7ZW5jfSE9IUFBQUFETEVpaWU3NGRTcldJQ2xLWlBzb013eTZyN3JYNnBxbVN3Nm9hR0U9IiwiZXhwIjoxNzU4Mjk2MTA1LCJfY2FjaGVJZCI6NzQyNjg3OCwiaWF0IjoxNzU4MjY3MzA1LCJqdGkiOiJJREdBS0ZIVkpHMDYxQVRDVFJRN1RDVFJRNzdUVjciLCJfYWJzb2x1dGVFeHBpcmF0aW9uVGltZSI6MTc1ODM1MzcwNX0.cyiEfsGNEu1KPejoeVfw3khTSe5sAdwWCsDW8zq_Amc' \
                --header 'Content-Type: application/json' \
                --data '{ "values": { "Detailed Description": "Github Action Run Status : Success;"} }'
